### PR TITLE
Add basic support for gemini models

### PR DESCRIPTION
**Pull request by ssonal**
Preliminary support for gemini. 

What's currently missing:
- Async
- Tool use

----

| :rocket: This description was created by [Ellipsis](https://www.ellipsis.dev) for commit 25c28bbaa9355dd9acd247882a34be4311a5bf84  | 
|--------|

### Summary:
This PR introduces basic support for Gemini models in the Instructor library, including a new client, updated documentation, and test cases.

**Key points**:
- Added basic support for Gemini models in the Instructor library.
- Introduced a new client for handling Gemini model interactions.
- Updated documentation and examples to include Gemini model usage.
- Added test cases for Gemini model functionality.
- Modified retry logic and response handling to accommodate Gemini-specific features.

----
Generated with :heart: by [ellipsis.dev](https://www.ellipsis.dev)

### CODE REVIEW

**Comment by jxnl** [comment]
can you add a note in the patching notes

**Comment by jxnl** [comment]
@ellipsis-dev can you try and update the documentation on patch.md docs

**Review by jxnl — CHANGES_REQUESTED** [review]
Can you jsut add docs to patch.md and the main readme

**Comment by ssonal** [comment]
Will try and get these in today @jxnl.

Also came across https://github.com/jxnl/instructor/pull/624, and it's best if we don't have to introduce new syntax. Taking a stab at standardising Gemini api calls as well.

**Comment by Cruppelt** [comment]
Out of curiosity - Is there a reason this isn't using the official function calling API? https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/function-calling

**Comment by ssonal** [comment]
> Out of curiosity - Is there a reason this isn't using the official function calling API? https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/function-calling

I have function calling on a branch but the responses are inconsistent and the response payload structure varies with every call. Not reliable enough to recommend at this time.

**Comment by jxnl** [comment]
1. are we ready to merge
2. lets move evals to https://github.com/instructor-ai/evals at some point, so lets not worry about that

**Comment by ssonal** [comment]
Yes this is good to go!

**Comment by jxnl** [comment]
whoo @ssonal found a bug in imports #697

**Pull request merged**
