### PR TITLE
feat: Add Async Support for Distill

### PR DESCRIPTION
**Pull request by tarunamasa**
### Description:
This update introduces significant enhancements to the distil() function, focusing on improved support for asynchronous programming. Key changes include:

Asyncio Integration:

The `_dispatch` and `_distil` methods have been augmented with their asynchronous counterparts _dispatch_async and _distil_async. This change enables the function to handle coroutine functions, allowing for asynchronous operations.
Async Await Syntax:

The async def and await keywords are now used in `_dispatch_async` and `_distil_async` to ensure proper asynchronous behavior. This modification is crucial for integrating with asyncio and handling concurrent tasks effectively.
Error Handling for Async Functions:

A new error check is added in `_dispatch_async` to enforce that the return type of the function must be a subclass of pydantic.BaseModel or an instance of it, ensuring consistency and type safety for asynchronous functions.
Conditional Execution Based on Coroutine Check:

The _dispatch and _distil functions now include a condition to check if fn is a coroutine function. Depending on this check, the appropriate synchronous or asynchronous version (`_dispatch_async`/`_distil_async` or `_dispatch`/`_distil`) is called. This change ensures that both synchronous and asynchronous functions can be handled by the same interface.
Adjustments to Function Wrappers:

The functools.wraps decorator is appropriately applied to the new asynchronous functions, maintaining the metadata of the original functions. This is important for introspection and debugging purposes.

----

| <a href="https://ellipsis.dev" target="_blank">Ellipsis</a> | :rocket: This PR description was created by [Ellipsis](https://www.ellipsis.dev) for commit f32d46257ea568c095902fcad973e4b551c622a2.  | 
|--------|--------|

### Summary:
This PR enhances the `distil` function in `instructor/distil.py` by adding async support, implementing async/await syntax, adding error handling for async functions, and adjusting function wrappers.

**Key points**:
- Added async support to `distil` function in `instructor/distil.py`.
- Introduced async versions of `_dispatch` and `_distil` methods.
- Implemented async/await syntax in `_dispatch_async` and `_distil_async`.
- Added error handling for async functions in `_dispatch_async`.
- Adjusted function wrappers with `functools.wraps` for new async functions.
- Included a condition to check if a function is a coroutine and call the appropriate function version.
----
Generated with :heart: by [ellipsis.dev](https://www.ellipsis.dev)

### CODE REVIEW

**Comment by tarunamasa** [comment]
Fixing the asyncopenai issue first

**Comment by jxnl** [comment]
Can you just add a task script to show that this is working?

**Comment by jxnl** [comment]
Are you still able to test this in add documentation? I can take a look next weekend.

**Comment by tarunamasa** [comment]
@jxnl will try to get some time to add this, I've tested it but need to write the tests 😖

**Pull request closed without merging**
