### PR TITLE
Integrate and Enhance Linting with Ruff

### PR DESCRIPTION
**Pull request by gao-hongnan**
Hi Jason and team,

I am proposing the addition of a `.ruff.toml` file to your repository to enhance and standardize the code formatting and linting process.

This pull request introduces a Ruff configuration that is largely based on the [**configuration**](https://github.com/openai/openai-python/blob/main/pyproject.toml) used in OpenAI's repository. The key aspects of this proposal are:

1. I  have adopted most rules verbatim from OpenAI, except for modifying the `line-length` to `88` instead of `120` to minimize disruption. Additionally, I've set the `target-version` to `3.9`, aligning with your repository's current Python version. I've also loosened the rules to allow `print` statements in the codebase.

2. I've added an `extend-per-file-ignores` section for `instructor/distil.py` to
   exclude `ARG002` (unused arguments). This is for your review, on
   whether the `base_model` argument should be removed from the following ([line 232](https://github.com/jxnl/instructor/blob/ffffab7b7b1389ae2327017ea85ce7b5e20390f7/instructor/distil.py#L232)):

    ```python
    def openai_kwargs(self, name, fn, args, kwargs, base_model):
    ```

Here's the brief summary on the changes (with reference to my previous **[PR](https://github.com/jxnl/instructor/pull/264)** on mypy):

✅ **Ruff Configuration File**: Closely aligned with the [OpenAI Python Ruff settings](https://github.com/openai/openai-python/blob/main/pyproject.toml). 

✅ **Ruff Pre-commit Integration**: `Ruff` has been integrated into the pre-commit hooks, targeting specifically the `instructor` directory.

✅ **Ruff GitHub Actions**:  Enhanced `Ruff` GitHub Actions for more detailed logging.

✅ **Ruff Artifacts Logs for Persistency**: Configured the workflow to generate and store `ruff` logs as artifacts. This provides a persistent record of the type checks for each build, useful for debugging and historical reference.

---

Currently, `Ruff` is configured to lint and format only the main `instructor` package. If there's a desire to include other packages or folders such as `tests` and `examples`, I'm more than willing to adjust the settings accordingly and assist in addressing any major or minor issues identified by `Ruff`.

## Summary by CodeRabbit

- **Refactor**
	- Enhanced GitHub Actions workflow for improved performance and added new steps for environment setup and artifact handling.

- **Chores**
	- Modified pre-commit hooks for better code formatting and linting.
	- Adjusted linting configurations and added exclusion settings.

- **Documentation**
	- Updated testing dependencies to ensure compatibility and stability.

### CODE REVIEW

**Comment by jxnl** [comment]
I thinking running it in tests and examples is great

**Comment by gao-hongnan** [comment]
> I thinking running it in tests and examples is great

Wow, that's a fast reply lol.

Okay, I will fix them by tomorrow, or latest by this weekend, so that `Ruff` will be up and running on both `tests` and `examples`. For complaints that is deemed to be more of a stylistic choice, I will temporarily add a "noqa" equivalent under the `.ruff.toml` config file's `[extend-per-file-ignores]` section (see screenshot).

Screenshot 2023-12-21 at 10 15 31 PM

**Comment by gao-hongnan** [comment]
I have added `examples` and `tests` packages for ruff to check in both local CI (`pre-commit`) and remote CI (`github actions`). Most ruff changes are minor, for example:

-   `examples/codegen-from-schema/create_fastapi_app.py`

    -   Fix `raise-without-from-inside-except (B904)` at `line 62`.

            ```diff
            def load_json_schema(json_schema_path: str) -> dict:
                try:
                    with open(json_schema_path) as f:
                        return json.load(f)
                except Exception as e:
            -        raise ValueError(f"Failed to load JSON schema: {e}")
            +        raise ValueError(f"Failed to load JSON schema: {e}") from e
            ```

-   `examples/chain-of-density/chain_of_density.py`

    -   Fix `loop-control-variable-not-used (B007)` at `line 118`.

            ```diff
            summary_chain.append(summary.summary)
            - for i in range(summary_steps):
            + for _i in range(summary_steps):
            ```
## ARG001 and ARG002

We ignore [Ruff's flake8-unused-arguments](https://docs.astral.sh/ruff/rules/#flake8-unused-arguments-arg) for a few selected files below:

```toml
[extend-per-file-ignores]
"instructor/distil.py" = ["ARG002"]
"tests/test_distil.py" = ["ARG001"]
"tests/test_patch.py" = ["ARG001"]
"examples/task_planner/task_planner_topological_sort.py" = ["ARG002"]
"examples/citation_with_extraction/main.py" = ["ARG001"]
```

The rationale of temporarily ignoring these rules:

>  Some of these arguments, although currently unused,
   might be intended for future use or expansion. Removing or altering them
   could unintentionally hinder the planned functionality. It's better to leave
   them as-is until there's a clear decision on how to proceed. However, I took
   the liberty to replace unused loop variables with a leading underscore `_` as
   a convention to indicate that they are intentionally unused. The difference
   is that these variables are not part of the function/method signature and are
   only used within the scope of the loop so it is safe to rename them.

`ARG001` and `ARG002` reference:

| Code   | Name                     | Message                          |
| ------ | ------------------------ | -------------------------------- |
| ARG001 | unused-function-argument | Unused function argument: {name} |
| ARG002 | unused-method-argument   | Unused method argument: {name}   |

**Comment by jxnl** [comment]
is this good to merge?

**Comment by gao-hongnan** [comment]
> is this good to merge?

Yes, it's good to merge! Thanks.

**Pull request merged**
