### PR TITLE
Implement Parallel Function Calls with `List[Union[T]]`

### PR DESCRIPTION
**Pull request by jxnl**
| <a href="https://ellipsis.dev" target="_blank">Ellipsis</a> | :rocket: This PR description was created by [Ellipsis](https://www.ellipsis.dev) for commit 82991b66c908c1438bfa47e10d3213b353dc352a.  | 
|--------|--------|

### Summary:
This PR introduces parallel function calls using a list of union types, modifies the instructor's patching mechanism to handle these calls, and includes tests for the new functionality.

**Key points**:
- Added `PARALLEL_TOOLS` to `Mode` enum in `instructor/function_calls.py`.
- Created `ParallelBase` class in `instructor/dsl/parallel.py` to handle parallel function calls.
- Modified `instructor/patch.py` to handle `PARALLEL_TOOLS` mode and use `ParallelBase` for response processing.
- Added tests for parallel function calls in `tests/openai/test_parallel.py`.
- Created an example of using parallel function calls in `examples/patching/pcalls.py`.
----
Generated with :heart: by [ellipsis.dev](https://www.ellipsis.dev)

### CODE REVIEW

**Comment by CyrusOfEden** [comment]
Would a change from Iterable[Union[…]] to tuple[…] or even just (…) be to your liking aesthetically? Happy to figure out the implementation and update this PR if you’re aligned

**Comment by jxnl** [comment]
> Would a change from Iterable[Union[…]] to tuple[…] or even just (…) be to your liking aesthetically? Happy to figure out the implementation and update this PR if you’re aligned

its not a tuple. its `Iterable[Union[T]]` once it streams

**Comment by CyrusOfEden** [comment]
> > Would a change from Iterable[Union[…]] to tuple[…] or even just (…) be to your liking aesthetically? Happy to figure out the implementation and update this PR if you’re aligned
> 
> its not a tuple. its `Iterable[Union[T]]` once it streams

I agree that that's the correct type, I'm updating my suggestion to passing a list of `[T1, T2, T3]` communicates the intent and is more terse

**Comment by jxnl** [comment]
> > > Would a change from Iterable[Union[…]] to tuple[…] or even just (…) be to your liking aesthetically? Happy to figure out the implementation and update this PR if you’re aligned
> > 
> > 
> > its not a tuple. its `Iterable[Union[T]]` once it streams
> 
> I agree that that's the correct type, I'm updating my suggestion to passing a list of `[T1, T2, T3]` communicates the intent and is more terse

we're going to use generics to reflect the type to the response. `[T1, T2, T3]` is not a typehint

resp: [T1, T2, T3] = create(response_model=[T1, T2, T3]) is not a thing

**Pull request merged**
