### PR TITLE
Anthropic client. Prevent empty generator when streaming

### LINKED ISSUE #727: Anthropic client is buggy
- [x] This is actually a bug report.
- [x] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [x] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [ ] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [ ] gpt-4
- [x] Other, Anthropic models

**Describe the bug**
I would like to use Anthropic client with `ANTHROPIC_TOOLS` mode.
I tested with Async / Non Async with stream=True / False.
Setting stream=True gives me empty result.
I am not entirely sure if this is Anthropic limitation or bug in Instructor.
I have tested all the cases below with OpenAI client, they work well.

**To Reproduce**

## Dependencies
```
instructor==1.3.2
anthropic==0.28
pydantic==2.7.2
```

## Initialize sync and async clients
```python
haiku_model = "claude-3-haiku-20240307"
sonnet_model = "claude-3-sonnet-20240229"

anthropic_client = Anthropic()
a_anthropic_client = AsyncAnthropic()

# Patched version
anthropic_client = instructor.Instructor(
    anthropic_client,
    create=instructor.patch(
        create=anthropic_client.messages.create, mode=instructor.Mode.ANTHROPIC_TOOLS
    ),
    provider=instructor.Provider.ANTHROPIC,
    mode=instructor.Mode.ANTHROPIC_TOOLS,
)

a_anthropic_client = instructor.AsyncInstructor(
    a_anthropic_client,
    create=instructor.patch(
        create=a_anthropic_client.messages.create, mode=instructor.Mode.ANTHROPIC_TOOLS
    ),
    provider=instructor.Provider.ANTHROPIC,
    mode=instructor.Mode.ANTHROPIC_TOOLS,
)


class User(BaseModel):
    name: str
    age: int
```

## Case 1: Sync

This on the correctness. With stream=False, I get the right results, but with stream=True, I got empty result.
I tried to replace haiku with sonnet, it gives me the same result.

```python
# This is OK
resp = anthropic_client.chat.completions.create(
    model=haiku_model,
    max_tokens=1024,
    messages=[
        {
            "role": "user",
            "content": "Extract Jason is 25 years old, Hannah is 20 years old.",
        }
    ],
    response_model=User,
    stream=False
)

print(resp)
# User(name='Jason', age=25)

# This is OK
resp = anthropic_client.chat.completions.create(
    model=haiku_model,
    max_tokens=1024,
    messages=[
        {
            "role": "user",
            "content": "Extract Jason is 25 years old, Hannah is 20 years old.",
        }
    ],
    response_model=Iterable[User],
    stream=False
)
for elem in resp:
    print(elem)
# name='Jason' age=25
# name='Hannah' age=20

# Now switch to stream, This is not OK, result is None
resp = anthropic_client.chat.completions.create(
    model=haiku_model,
    max_tokens=1024,
    messages=[
        {
            "role": "user",
            "content": "Extract Jason is 25 years old, Hannah is 20 years old.",
        }
    ],
    response_model=Iterable[User],
    stream=True
)

for elem in resp:
    print(elem)
```

## Case 2: Async
Similar as above. stream=True gives me empty result 

```python
# async + non-iterable, This is OK
resp = await a_anthropic_client.chat.completions.create(
    model=haiku_model,
    max_tokens=1024,
    messages=[
        {
            "role": "user",
            "content": "Extract Jason is 25 years old, Hannah is 20 years old.",
        }
    ],
    response_model=User,
    stream=False,
)

print(resp)
# name='Jason' age=25

# async + iterable + non-stream, This is OK
resp = await a_anthropic_client.chat.completions.create(
    model=haiku_model,
    max_tokens=1024,
    messages=[
        {
            "role": "user",
            "content": "Extract Jason is 25 years old, Hannah is 20 years old.",
        }
    ],
    response_model=Iterable[User],
    stream=False
)

for elem in resp:
    print(elem)
# name='Jason' age=25
# name='Hannah' age=20

# async + iterable + stream, This is not OK, result is empty
resp = await a_anthropic_client.chat.completions.create(
    model=haiku_model,
    max_tokens=1024,
    messages=[
        {
            "role": "user",
            "content": "Extract Jason is 25 years old, Hannah is 20 years old.",
        }
    ],
    response_model=Iterable[User],
    stream=True
)

async for elem in resp:
    print(elem)
```

**Expected behavior**
Stream result should be the same as non-stream result.

### PR DESCRIPTION
**Pull request by lemontheme**
This commit fixes #727.

When using the Anthropic client in streaming (stream=true) mode, an empty generator was returned, even though the LLM model response was non-empty. This was caused by completion text being looked for in
the wrong place on the Anthopic SDK's completion chunk object. (I'm guessing something changed in an update.) In the method `extract_json()` in dsl/iterable.py, this is where completion text was looked for previously:

```
chunk.model_extra.get("delta", "").get("partial_json", "")
```

The attribute `model_extra`, however, is an empty
dict. The first `.get()` therefore gives a string, causing the second `.get()` to raise an AttributeError. That exception was silently swallowed, since the whole block is wrapped in a try-except with a `pass` on the except path.

In the Antropic SDK, `delta` is now an attribute
and no dicts are involved.

Updating the line above as follows fixes the issue:

```
chunk.delta.partial_json
```

I've applied this fix in both iterable.py
and partial.py. I've tested both with `Iterable[]` and `Partial[]` and with with modes ANTHROPIC_TOOLS and ANTHROPIC_JSON. I've also tested `create_iterable()` and `create_partial()`. While testing the last part I removed the guard that prevented Anthropic being used in this mode. Everything seems to work fine,
so I've dropped it.

----

| :rocket: | This description was created by [Ellipsis](https://www.ellipsis.dev) for commit fee73bea11c012675d1b28b26cc1667adfa91857  | 
|--------|--------|

### Summary:
This PR fixes an issue with the Anthropic client returning an empty generator in streaming mode by correcting attribute access in the extraction functions and removing a usage guard.

**Key points**:
- Fixed incorrect attribute access in `extract_json()` in `iterable.py` and `partial.py`.
- Removed guard in `client.py` preventing Anthropic use in iterable mode.
- Tested changes with various modes and functions.

----
Generated with :heart: by [ellipsis.dev](https://www.ellipsis.dev)

### CODE REVIEW

**Comment by jxnl** [comment]
are we importing out of the beta extension?

**Comment by fer-git** [comment]
@jxnl When I file this issue #727, I already used the latest Anthropic client, the tool feature is already out of beta.
And last week, PR #723 from @lemontheme ensures Instructor is using non-beta tool feature.

This current PR from @lemontheme  is the continuation of adapting new Anthropic schema after non-beta tool feature is released.

**Comment by lemontheme** [comment]
@fer-git summarizes the situation well!

We're adapting to changes in the Anthropic client SDK, the minimum required version of which was bumped to 0.27 on main by my previous PR.

**Comment by lemontheme** [comment]
Out of curiosity, since this PR is now 2 weeks old, is there anything you'd like to see different, @jxnl, to consider merging it –e.g. better backwards compatibility with older Anthropic client versions, tests, ...?

With the latest 1.3.3 release, the issue this PR addresses is going to become more prevalent.

**Review by jxnl — APPROVED** [review]

**Pull request merged**
