### PR TITLE
Deprecated FUNCTIONs mode

### PR DESCRIPTION
**Pull request by Phodaie**
## Summary by CodeRabbit

- **New Features**
	- Introduced a `TOOLS` mode to replace the deprecated `FUNCTIONS` mode.

- **Bug Fixes**
	- Updated function signatures to use the new `TOOLS` mode for consistency.

- **Refactor**
	- Enhanced test function to include benchmarking capabilities.

- **Deprecations**
	- Issued a deprecation warning for the 'FUNCTIONS' mode, guiding users towards the new 'TOOLS' mode.

### CODE REVIEW

**Comment by jxnl** [comment]
you're on a super old version `version = "0.3.6"`

**Comment by jxnl** [comment]
are you able to resolve the merge issues?

**Comment by Phodaie** [comment]
should I just create a new PR for the latest version and decline this PR?

**Comment by jxnl** [comment]
ok we can do that!

**Pull request closed without merging**
