### PR TITLE
async gemini support

### PR DESCRIPTION
**Pull request by Cruppelt**
| :rocket: | This description was created by [Ellipsis](https://www.ellipsis.dev) for commit b1602cb76a9d13029d08cc0f3bbc8b92e34dedaf  | 
|--------|--------|

### Summary:
This PR introduces asynchronous support to the `from_gemini` function in the `instructor/client_gemini.py`, allowing it to handle both synchronous and asynchronous operations.

**Key points**:
- Added async support in `from_gemini` function in `instructor/client_gemini.py`
- Overloads added for `from_gemini` to handle sync and async modes
- Conditional logic based on `use_async` to return appropriate instructor type
- Uses `generate_content_async` for async and `generate_content` for sync

----
Generated with :heart: by [ellipsis.dev](https://www.ellipsis.dev)

### CODE REVIEW

**Comment by Cruppelt** [comment]
lmk thoughts on the use_async - The other clients have different Async clients that we can check the instance of but in this case Google/Gemini has the same client.

**Review by jxnl — APPROVED** [review]

**Comment by jxnl** [comment]
Honestly, this looks good. Have you tested it locally yet?

**Comment by Cruppelt** [comment]
> Honestly, this looks good. Have you tested it locally yet?

Yes, typehead working too.

image

**Comment by ssonal** [comment]
retry.py retry_async logic needs to also be updated to handle ValidationErrors. Gemini uses a different messages format.

**Comment by Cruppelt** [comment]
> retry.py retry_async logic needs to also be updated to handle ValidationErrors. Gemini uses a different messages format.

Have an example that will break? Happy to add

**Comment by ssonal** [comment]
> > retry.py retry_async logic needs to also be updated to handle ValidationErrors. Gemini uses a different messages format.
> 
> Have an example that will break? Happy to add

Just saying that https://github.com/jxnl/instructor/blob/3d8d4495edd6740fff2f1bfbb0335b198f01f0dd/instructor/retry.py#L159-L169 and https://github.com/jxnl/instructor/blob/3d8d4495edd6740fff2f1bfbb0335b198f01f0dd/instructor/retry.py#L225-L232 should match. 

`GEMINI_JSON` mode requires different handling of args for retries.

**Pull request merged**
