### PR TITLE
fix: remove URLs in pydantic error messages

### LINKED ISSUE #509: Pydantic includes URLs with validation errors which aren't useful for the LLM
**Is your feature request related to a problem? Please describe.**

Pydantic includes a URL by default to look up more information on the error which isn't useful for the LLM and also takes up token space.

```
1 validation error for Boop
name
  Value error, 'bla' is not a valid boop. [type=value_error, input_value='bla', input_type=str]
    For further information visit https://errors.pydantic.dev/2.6/v/value_error
```

**Describe the solution you'd like**
It'd be nice to have more control over what happens here. Pydantic let's you dump the errors if you catch the exception via `errors(` and then specify `include_url`. It feels like the default should be to not include that.

**Describe alternatives you've considered**
Just giving more control over the reask flow could let people solve this themselves.

### PR DESCRIPTION
**Pull request by ssonal**
Fixes #509

Pydantic includes error URLs in ValidationErrors which means extra tokens used in LLM calls.

Pydantic relies on an environment variable to control this setting and is on by default. https://github.com/pydantic/pydantic-core/blob/e1fc99dd3207157aad77defc20ab6873fd268b5b/python/pydantic_core/_pydantic_core.pyi#L818

This change sets the environment variable dynamically when the package is invoked.

----

| :rocket: This description was created by [Ellipsis](https://www.ellipsis.dev) for commit 5c2a35961c141c39afd1c83286195548dbf86b24  | 
|--------|

### Summary:
This PR sets an environment variable to remove URLs from Pydantic error messages and includes a test to verify the change.

**Key points**:
- Set `PYDANTIC_ERRORS_INCLUDE_URL` to `0` in `set_env_variable` in `/instructor/utils.py`
- Call `set_env_variable` in `/instructor/__init__.py`
- Add test in `/tests/test_function_calls.py` to verify URLs are not in Pydantic error messages

----
Generated with :heart: by [ellipsis.dev](https://www.ellipsis.dev)

### CODE REVIEW

**Comment by jxnl** [comment]
I would prefer this to be a piece of the documentation rather than something that we force users to use.

**Comment by ssonal** [comment]
This does sound like a sane default to me, especially when retries come into the picture. Would be cumbersome to have to set this env variable each time. But maybe something like a config file makes more sense instead?

**Comment by Mr-Ruben** [comment]
I have been waiting for this fix since March-2024.

I am with @ssonal   
Who wants a useless url in the error message?  (+noise, +tokens, no benefit)
Just document how to enable if someone ever wants and move on.

**Comment by jxnl** [comment]
see #757

**Pull request closed without merging**
