### PR TITLE
chore: Include types to instructor.patch

### PR DESCRIPTION
**Pull request by savarin**
This PR adds types to the following files, as per https://github.com/jxnl/instructor/issues/390.

```
instructor/patch.py
tests/test_patch.py
```

----

| <a href="https://ellipsis.dev" target="_blank">Ellipsis</a> | :rocket: This PR description was created by [Ellipsis](https://www.ellipsis.dev) for commit 26a57a899045af56ef008c46c87b8b2e8aa1dd37.  | 
|--------|--------|

### Summary:
This PR adds type annotations to `instructor/patch.py` and `tests/test_patch.py`, and includes these files in the MyPy check in `.github/workflows/mypy.yml`.

**Key points**:
- Added type annotations to `instructor/patch.py` and `tests/test_patch.py`.
- Updated `.github/workflows/mypy.yml` to include these files in MyPy check.
- Made minor code adjustments in `instructor/patch.py` for type correctness.
----
Generated with :heart: by [ellipsis.dev](https://www.ellipsis.dev)

### CODE REVIEW

**Comment by savarin** [comment]
@jxnl FYI I got mypy to pass but had to remove generics.

**Comment by jxnl** [comment]
@lukevs how much will this fuck up the client pr?

**Comment by savarin** [comment]
> @lukevs how much will this fuck up the client pr?

@lukevs Let me know what works best here. Happy to merge this one first and I'll help update your PR, or merge your PR first and I'll refresh this one. Thanks!

**Comment by lukevs** [comment]
Taking a look now

**Comment by lukevs** [comment]
These are fine for now. I'm close on types for the clients themselves which will change some of this logic, so I'm not attached to what's currently in main.

**Comment by savarin** [comment]
> These are fine for now. I'm close on types for the clients themselves which will change some of this logic, so I'm not attached to what's currently in main wrt the TypeVar / Params

@lukevs Sounds good, let me if I can help!

**Comment by savarin** [comment]
> These are fine for now. I'm close on types for the clients themselves which will change some of this logic, so I'm not attached to what's currently in main wrt the TypeVar / Params

@jxnl Let me know if you have any more thoughts - thanks!

**Pull request merged**
