### PR TITLE
feat(client,function_calls,process_response,test_new_client): enhance create method to handle multiple responses

### PR DESCRIPTION
**Pull request by jxnl**
| <a href="https://ellipsis.dev" target="_blank">Ellipsis</a> | :rocket: This PR description was created by [Ellipsis](https://www.ellipsis.dev) for commit bfa4ca14fff73c2d2c28485230933bcdc83fa595.  | 
|--------|--------|

### Summary:
This PR enhances the `create` method to handle multiple responses from the OpenAI API, updates various methods in `function_calls.py` and `process_response.py` to handle multiple responses, and includes a test for multiple responses in `test_new_client.py`.

**Key points**:
- Overloaded `create` method in `client.py` to handle multiple responses.
- Updated `handle_kwargs` method in `client.py` to include `n` parameter in kwargs.
- Updated `function_calls.py` to handle multiple responses in `parse_functions`, `parse_tools`, and `parse_json` methods.
- Updated `process_response.py` to attach raw response to each model in case of IterableBase response model.
- Updated `test_new_client.py` to include a test for multiple responses.

----
Generated with :heart: by [ellipsis.dev](https://www.ellipsis.dev)

### CODE REVIEW

**Comment by jxnl** [comment]
@ellipsis-dev can you fix the merge conflicts

**Comment by josepablog** [comment]
Why was this closed without merge? Interested in this feature

**Comment by jxnl** [comment]
too many conflicts, didnt know if people really needed this

**Comment by thomasahle** [comment]
Multiple responses would be incredibly useful to have.
I'm trying to do something like [Getting 50% (SoTA) on ARC-AGI with GPT-4o](https://www.lesswrong.com/posts/Rdwui3wHxCeKb7feK/getting-50-sota-on-arc-agi-with-gpt-4o), and it requires drawing thousands of independent samples.

**Comment by xinyiliu128** [comment]
we also have this kind of use cases where we want to generate multiple individual samples in one call. it would be great if you can reopen and merge this PR!

**Pull request closed without merging**
