### PR TITLE
Ollama part2

### PR DESCRIPTION
**Pull request by jxnl**

### CODE REVIEW

**Comment by Tedfulk** [comment]
Hey @jxnl thanks for taking the time to look at it! Unfortunately I am still having the same issue of passing a larger context and it's unable to correct itself to proper json. This is a random example I was trying it on. I'll keep working on it. 
```python
from litellm import completion, provider_list
from pydantic import BaseModel

import instructor
from instructor.patch import wrap_chatcompletion

litellm_completion = wrap_chatcompletion(func=completion, mode=instructor.Mode.MD_JSON)


class Car(BaseModel):
    make: str
    model: str
    year: int
    color: str
    plate_number: str
    racing_stripe: bool


data = """
My favorite car, the 2019 Ford Mustang GT, has been a dream of mine since childhood. My dad owned one when he was younger, igniting my passion for this iconic vehicle. The Mustang GT, known for its powerful engine and sleek design, represents more than just a mode of transportation; it's a symbol of freedom and strength. I remember the stories my dad would tell about the adventures he had with his Mustang, the roar of the engine, and the sense of excitement it brought to every journey. These tales deeply ingrained in me a love for this car.

My ideal Mustang GT would be in a stunning baby blue color, a shade that stands out and captures the essence of its high-spirited nature. The racing stripe down the center would be a classic addition, enhancing its sporty appearance and paying homage to its racing heritage. This stripe, possibly in a contrasting color like white or black, would run from the front bumper to the rear, accentuating the car's aerodynamic lines.

The personalized license plate, 1BADGT, is a playful yet fitting tribute to the car's prowess. It's a declaration of the car's capability and my own connection to it. Inside, I envision a custom interior that blends luxury with functionality. Leather seats with blue stitching, a state-of-the-art sound system, and a dashboard equipped with the latest technology would make the driving experience even more enjoyable.

Under the hood, the Mustang GT's powerful V8 engine would be a marvel of engineering, delivering exceptional performance and a thrilling driving experience. The rumble of the engine would be music to my ears, a reminder of the car's raw power and agility. I imagine taking it on long drives, feeling the responsive handling and the rush of acceleration.

This car wouldn't just be a means of travel; it would be a companion on the road, a source of joy and a fulfillment of a childhood dream inspired by my dad's own Mustang adventures. Every time I'd sit behind the wheel, I'd feel a deep connection to its legacy and a sense of pride in owning a piece of automotive history. The 2019 Ford Mustang GT, in my dream baby blue with a racing stripe, would be more than just a car; it would be a cherished possession, a symbol of my passion, and a link to cherished family memories.
"""

# data = """
# My favorite car is a 2019 Ford Mustang GT. My dad had one when he was little and Have always wanted one since I was a little boy my license plate is 1BADGT. And I would love for it to be a baby blue color with a racing stripe down the center.
# """
car = litellm_completion(
    model="ollama/llama2",
    response_model=Car,
    messages=[
        {
            "role": "system",
            "content": "You are a JSON extractor. Please extract the following into JSON format, No Talk.",
        },
        {
            "role": "user",
            "content": f"Extract: {data}",
        },
    ],
    api_base="http://localhost:11434",
    # max_retries=2,
)

print("CAR = ", car.model_dump_json())
```

**Comment by Tedfulk** [comment]
then the error when I run it. 

```bash
Retrying, exception: 1 validation error for Car
  Invalid JSON: trailing characters at line 10 column 1 [type=json_invalid, input_value='{\n  "make": "Ford",\n  ...on, please let me know.', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/json_invalid
Traceback (most recent call last):
  File "/Users/tedfulk/repos/personal/instructor/instructor/patch.py", line 309, in retry_sync
    return process_response(
  File "/Users/tedfulk/repos/personal/instructor/instructor/patch.py", line 168, in process_response
    model = response_model.from_response(
  File "/Users/tedfulk/repos/personal/instructor/instructor/function_calls.py", line 175, in from_response
    return cls.model_validate_json(
  File "/Users/tedfulk/repos/personal/instructor/.venv/lib/python3.10/site-packages/pydantic/main.py", line 532, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Car
  Invalid JSON: trailing characters at line 10 column 1 [type=json_invalid, input_value='{\n  "make": "Ford",\n  ...on, please let me know.', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/json_invalid
Retrying, exception: 1 validation error for Car
  Invalid JSON: expected value at line 1 column 1 [type=json_invalid, input_value='Sure! Here is the JSON o... any further questions!', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/json_invalid
Traceback (most recent call last):
  File "/Users/tedfulk/repos/personal/instructor/instructor/patch.py", line 309, in retry_sync
    return process_response(
  File "/Users/tedfulk/repos/personal/instructor/instructor/patch.py", line 168, in process_response
    model = response_model.from_response(
  File "/Users/tedfulk/repos/personal/instructor/instructor/function_calls.py", line 175, in from_response
    return cls.model_validate_json(
  File "/Users/tedfulk/repos/personal/instructor/.venv/lib/python3.10/site-packages/pydantic/main.py", line 532, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Car
  Invalid JSON: expected value at line 1 column 1 [type=json_invalid, input_value='Sure! Here is the JSON o... any further questions!', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/json_invalid
Max retries reached, exception: 1 validation error for Car
  Invalid JSON: expected value at line 1 column 1 [type=json_invalid, input_value='Sure! Here is the JSON o... any further questions!', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/json_invalid
Traceback (most recent call last):
  File "/Users/tedfulk/repos/personal/instructor/examples/ollama/run.py", line 71, in <module>
    car = litellm_completion(
  File "/Users/tedfulk/repos/personal/instructor/instructor/patch.py", line 392, in new_chatcompletion_sync
    response = retry_sync(
  File "/Users/tedfulk/repos/personal/instructor/instructor/patch.py", line 346, in retry_sync
    raise e
  File "/Users/tedfulk/repos/personal/instructor/instructor/patch.py", line 309, in retry_sync
    return process_response(
  File "/Users/tedfulk/repos/personal/instructor/instructor/patch.py", line 168, in process_response
    model = response_model.from_response(
  File "/Users/tedfulk/repos/personal/instructor/instructor/function_calls.py", line 175, in from_response
    return cls.model_validate_json(
  File "/Users/tedfulk/repos/personal/instructor/.venv/lib/python3.10/site-packages/pydantic/main.py", line 532, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Car
  Invalid JSON: expected value at line 1 column 1 [type=json_invalid, input_value='Sure! Here is the JSON o... any further questions!', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/json_invalid
```

**Comment by jxnl** [comment]
Yeah, honestly it just looks like without function calling llama sucks

**Comment by jxnl** [comment]
I'm likely gonna keep this at won't try to fix until we have better function calling. from ollama or litellm. which is probably sub 1% of all users rn. best shot is better prompt engineering rather than something that instructor will try to do for you.

**Comment by jxnl** [comment]
I'd add some "no talking" type prompts but again, better off not using useless open models that are not mean for structured output.

**Pull request merged**
