### PR TITLE
Maintain the rest of the input arguments to create

### PR DESCRIPTION
**Pull request by lukevs**
image

----

| <a href="https://ellipsis.dev" target="_blank">Ellipsis</a> | :rocket: This PR description was created by [Ellipsis](https://www.ellipsis.dev) for commit c58b786dc407069a897419f85e1f6e30f5ab258f.  | 
|--------|--------|

### Summary:
The PR enhances the `InstructorChatCompletionCreate` class and the `patch` function in `instructor/patch.py` to support generic parameters for input arguments and return type.

**Key points**:
- Modified `InstructorChatCompletionCreate` class in `instructor/patch.py` to inherit from `Protocol` and `Generic[T_ParamSpec, T_Model]`.
- Updated `patch` function to return an instance of `InstructorChatCompletionCreate` with the generic parameters `T_ParamSpec` and `T_Model`.
----
Generated with :heart: by [ellipsis.dev](https://www.ellipsis.dev)

### CODE REVIEW

**Comment by jxnl** [comment]
this doesnt add `response_model` and etc  right?

**Comment by lukevs** [comment]
No it still does 
image

**Comment by lukevs** [comment]
image
It's just an additional hint to help with args / kwargs

**Comment by lukevs** [comment]
Oddly I'm getting argument suggestion, but not types on the arguments themselves 
image

**Pull request merged**
