### PR TITLE
feat: support anthropic (non-streaming only)

### PR DESCRIPTION
**Pull request by shreya-51**
| <a href="https://ellipsis.dev" target="_blank">Ellipsis</a> | :rocket: This PR description was created by [Ellipsis](https://www.ellipsis.dev) for commit 584eb5c8eefbac185322f50a043060f5d65fd1a6.  | 
|--------|--------|

### Summary:
This PR adds support for the Anthropic AI model to the Instructor library by introducing a new mode and utility functions for handling XML, and includes tests for the new functionality.

**Key points**:
- Added `ANTHROPIC_TOOLS` mode in `instructor/mode.py`
- Modified `instructor/function_calls.py` to handle the new mode
- Added utility functions in `instructor/anthropic_utils.py` for JSON to XML conversion and vice versa
- Modified `instructor/process_response.py` and `instructor/retry.py` to handle the new mode
- Added new dependencies in `pyproject.toml` and `requirements.txt`
- Added tests for the new functionality in `tests/anthropic/test_simple.py`

----
Generated with :heart: by [ellipsis.dev](https://www.ellipsis.dev)

### CODE REVIEW

**Comment by jxnl** [comment]
let me know when this is good to merge :)

**Comment by shreya-51** [comment]
> let me know when this is good to merge :)

should be good now

**Comment by jxnl** [comment]
the follow does not work

```python
from pydantic import BaseModel
from typing import List
import anthropic
import instructor

# Patching the Anthropics client with the instructor for enhanced capabilities
anthropic_client = instructor.patch(
    create=anthropic.Anthropic().messages.create, mode=instructor.Mode.ANTHROPIC_TOOLS
)

class Properties(BaseModel):
    key: str
    value: List[str]

class User(BaseModel):
    name: str
    age: int
    properties: List[Properties]

user_response = anthropic_client(
    model="claude-3-haiku-20240307",
    max_tokens=1024,
    max_retries=0,
    messages=[
        {
            "role": "user",
            "content": "Create a user for a model with a name, age, and properties.",
        }
    ],
    response_model=User,
)  # type: ignore

print(user_response.model_dump_json(indent=2))
```

**Comment by jxnl** [comment]
@shreya-51 mind skipping the tests using `pytest.mark.skip` and changing the model to use haiku?

**Comment by slavakurilyak** [comment]
@shreya-51 what about [streaming messages](https://docs.anthropic.com/claude/reference/messages-streaming) support? This is very important for user experience.

**Pull request merged**
